{{ config(materialized='table')}}

with CUSTOMERORDERS as(

select C.CUSTOMERID, CONCAT(C.FIRSTNAME,' ', C.LASTNAME) AS CUSTOMERNAME,COUNT(O.ORDERID) AS NO_OF_ORDERS 
from L1_LANDING.CUSTOMERS C
JOIN L1_LANDING.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERID, CUSTOMERNAME
ORDER BY NO_OF_ORDERS DESC
)

SELECT CUSTOMERID, CUSTOMERNAME, NO_OF_ORDERS
FROM CUSTOMERORDERS


